name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

    build-linux-musl:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4.1.1
     - name: Install cross
       run: cargo install cross
     - name: Build for Alpine (musl)
       run: cross build --target x86_64-unknown-linux-musl --release
     - uses: actions/upload-artifact@v4
       with:
        name: alpine-linux-artifact
        path: target/x86_64-unknown-linux-musl/release/*.so
