name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  build-linux-musl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Install cross
      run: cargo install cross
    - name: Build for Alpine (musl)
      run: cross build --target x86_64-unknown-linux-musl --release
    - uses: actions/upload-artifact@v4
      with:
        name: alpine-linux-artifact
        path: target/release/release/musl_*.so
        
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Build
      run: cargo build --release -v
    - uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: target/release/*.so

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Build
      run: cargo build --release -v
    - uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: target/release/*.dll

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build
        run: cargo build --release -v
      - uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: target/release/*.dylib
